capture program drop neighbors
program define neighbors , rclass
	syntax namelist , source(varname) dest(varname)
{
	gen `1' = 0
	replace  `1' = 1 if `source' == "AK"  & inlist(`dest',"WA")
	replace  `1' = 1 if `source' == "AL"  & inlist(`dest',"TN","GA","FL","MS")
	replace  `1' = 1 if `source' == "AR"  & inlist(`dest',"MO","TN","MS","LA","TX","OK")
	replace  `1' = 1 if `source' == "AZ"  & inlist(`dest',"UT","CO","NM","CA","NV")
	replace  `1' = 1 if `source' == "CA"  & inlist(`dest',"OR","NV","AZ","HI")
	replace  `1' = 1 if `source' == "CO"  & inlist(`dest',"WY","NE","KS","OK","NM","AZ","UT")
	replace  `1' = 1 if `source' == "CT"  & inlist(`dest',"MA","RI","NY")
	replace  `1' = 1 if `source' == "DC"  & inlist(`dest',"MD","VA")
	replace  `1' = 1 if `source' == "DE"  & inlist(`dest',"PA","NJ","MD")
	replace  `1' = 1 if `source' == "FL"  & inlist(`dest',"GA","AL")
	replace  `1' = 1 if `source' == "GA"  & inlist(`dest',"NC","SC","FL","AL","TN")
	replace  `1' = 1 if `source' == "HI"  & inlist(`dest',"CA")
	replace  `1' = 1 if `source' == "IA"  & inlist(`dest',"MN","WI","IL","MO","NE","SD")
	replace  `1' = 1 if `source' == "ID"  & inlist(`dest',"MT","WY","UT","NV","OR","WA")
	replace  `1' = 1 if `source' == "IL"  & inlist(`dest',"WI","IN","KY","MO","IA")
	replace  `1' = 1 if `source' == "IN"  & inlist(`dest',"MI","OH","KY","IL")
	replace  `1' = 1 if `source' == "KS"  & inlist(`dest',"NE","MO","OK","CO")
	replace  `1' = 1 if `source' == "KY"  & inlist(`dest',"OH","WV","VA","TN","MO","IL","IN")
	replace  `1' = 1 if `source' == "LA"  & inlist(`dest',"AR","MS","TX")
	replace  `1' = 1 if `source' == "MA"  & inlist(`dest',"NH","RI","CT","NY","VT")
	replace  `1' = 1 if `source' == "MD"  & inlist(`dest',"PA","DE","DC","VA","WV")
	replace  `1' = 1 if `source' == "ME"  & inlist(`dest',"NH")
	replace  `1' = 1 if `source' == "MI"  & inlist(`dest',"OH","IN","WI")
	replace  `1' = 1 if `source' == "MN"  & inlist(`dest',"WI","IA","SD","ND")
	replace  `1' = 1 if `source' == "MO"  & inlist(`dest',"IA","IL","KY","TN","AR","OK","KS","NE")
	replace  `1' = 1 if `source' == "MS"  & inlist(`dest',"TN","AL","LA","AR")
	replace  `1' = 1 if `source' == "MT"  & inlist(`dest',"ND","SD","WY","ID")
	replace  `1' = 1 if `source' == "NC"  & inlist(`dest',"VA","SC","GA","TN")
	replace  `1' = 1 if `source' == "ND"  & inlist(`dest',"MN","SD","MT")
	replace  `1' = 1 if `source' == "NE"  & inlist(`dest',"SD","IA","MO","KS","CO","WY")
	replace  `1' = 1 if `source' == "NH"  & inlist(`dest',"ME","MA","VT")
	replace  `1' = 1 if `source' == "NJ"  & inlist(`dest',"NY","DE","PA")
	replace  `1' = 1 if `source' == "NM"  & inlist(`dest',"CO","OK","TX","AZ","UT")
	replace  `1' = 1 if `source' == "NV"  & inlist(`dest',"ID","UT","AZ","CA","OR")
	replace  `1' = 1 if `source' == "NY"  & inlist(`dest',"VT","MA","CT","NJ","PA")
	replace  `1' = 1 if `source' == "OH"  & inlist(`dest',"PA","WV","KY","IN","MI")
	replace  `1' = 1 if `source' == "OK"  & inlist(`dest',"KS","MO","AR","TX","NM","CO")
	replace  `1' = 1 if `source' == "OR"  & inlist(`dest',"WA","ID","NV","CA")
	replace  `1' = 1 if `source' == "PA"  & inlist(`dest',"NY","NJ","DE","MD","WV","OH")
	replace  `1' = 1 if `source' == "RI"  & inlist(`dest',"MA","CT")
	replace  `1' = 1 if `source' == "SC"  & inlist(`dest',"NC","GA")
	replace  `1' = 1 if `source' == "SD"  & inlist(`dest',"ND","MN","IA","NE","WY","MT")
	replace  `1' = 1 if `source' == "TN"  & inlist(`dest',"KY","VA","NC","GA","AL","MS","AR","MO")
	replace  `1' = 1 if `source' == "TX"  & inlist(`dest',"OK","AR","LA","NM")
	replace  `1' = 1 if `source' == "UT"  & inlist(`dest',"ID","WY","CO","NM","AZ","NV")
	replace  `1' = 1 if `source' == "VA"  & inlist(`dest',"MD","DC","NC","TN","KY","WV")
	replace  `1' = 1 if `source' == "VT"  & inlist(`dest',"NH","MA","NY")
	replace  `1' = 1 if `source' == "WA"  & inlist(`dest',"AK","ID","OR")
	replace  `1' = 1 if `source' == "WI"  & inlist(`dest',"MI","IL","IA","MN")
	replace  `1' = 1 if `source' == "WV"  & inlist(`dest',"PA","MD","VA","KY","OH")
	replace  `1' = 1 if `source' == "WY"  & inlist(`dest',"MT","SD","NE","CO","UT","ID")
}
end
